### PR TITLE
maimaiDX BUDDiES Setup

### PR DESCRIPTION
**Pull request by alfredodeux**
Initial guide for setting up maimai. Still work to do on troubleshooting and controllers.

### CODE REVIEW

**Comment by akitakedits** [comment]
Any update on this?

**Comment by alfredodeux** [comment]
> Any update on this to implement what we'd talked about on Discord?

Yes - give me a day or two. To summarize the changes:
1. discord can host unpacked binaries and icf files
2. keep it simple so that there's less variability in user installations
3. remove artemis step-by-step and other over-detailed sections

**Comment by alfredodeux** [comment]
@akitakedits ready for review

**Comment by akitakedits** [comment]
Looks good enough to at least push out and see what happens.
If there are mistakes or further changes needed we'll just iterate over time.

Thanks for your work!

**Pull request merged**
